---
version: '3'

volumes:
  cowrie-etc:
  cowrie-var:

services:
  cowrie:
    restart: always
    build:
      context: context
      dockerfile: Dockerfile
    ports:
      - "22:22"
      - "23:23"
    volumes:
      - cowrie-etc:/cowrie/cowrie-git/etc
      - cowrie-var:/cowrie/cowrie-git/var
